In [6]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import datasets


In [12]:
X, y = datasets.load_iris(return_X_y=True, as_frame=True)
(X.shape, y.shape)

((150, 4), (150,))

In [15]:
# The dataset is balanced
y.value_counts()

0    50
1    50
2    50
Name: target, dtype: int64

In [13]:
# Split dataset into train / test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [14]:
clf = LogisticRegression(random_state=42)
clf.fit(X_train, y_train)

LogisticRegression()

In [11]:
pred = clf.predict(X_test)
pred

array([1, 2, 0, 0, 2, 1, 2, 2, 0, 0, 0, 0, 1, 1, 1, 0, 2, 0, 0, 0, 0, 2,
       1, 2, 2, 1, 2, 2, 1, 1, 2, 0, 1, 2, 1, 1, 1, 2])

In [16]:
clf.score(X_test, y_test)


0.9210526315789473

In [20]:
# Train model using k-fold cross validation
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X, y)
clf_k_fold = LogisticRegression(random_state=42)
scores = cross_val_score(clf_k_fold,X=X, y=y, cv=5)

In [21]:
scores

array([0.96666667, 1.        , 0.93333333, 0.9       , 1.        ])

In [22]:
# Create pipeline
from sklearn.pipeline import make_pipeline
clf = make_pipeline(StandardScaler(), LogisticRegression())
cross_val_score(clf, X, y, cv=5)


array([0.96666667, 1.        , 0.93333333, 0.9       , 1.        ])